prompt_assets:
  base_path: "assets/prompts"
  images:
    test_1: "images/init_test_image.jpg"
    test_2: "images/init_test_image_2.jpg"
    test_3: "images/init_test_image_3.jpg"
    out_1: "images/init_test_image_toy_1.png"
    out_1_v2: "images/init_test_image_toy_1v2.png"
    out_2: "images/init_test_image_toy_2.jpg"
    out_2_v2: "images/init_test_image_toy_2v2.jpg"
    out_2_v3: "images/init_test_image_toy_2v3.png"
    out_3: "images/init_test_image_toy_3.png"
    out_3_v2: "images/init_test_image_toy_3v2.jpeg"
    out_3_v3: "images/init_test_image_toy_3v3.jpeg"

prompts:
  keyword_extractor:
    system_prompt: "prompts/keyword_extractor/system.txt"
    task_prompt: "prompts/keyword_extractor/task.txt"
    example_sequence:
      - type: "text"
        content: "prompts/keyword_extractor/init_objective_define.txt"
      - type: "text"
        content: "prompts/keyword_extractor/example1_input.txt"
      - type: "image"
        content: "test_1"
      - type: "text"
        content: "prompts/keyword_extractor/example1_output.txt"
      - type: "text"
        content: "prompts/keyword_extractor/example2_input.txt"
      - type: "image"
        content: "test_2"
      - type: "text"
        content: "prompts/keyword_extractor/example2_output.txt"
      - type: "text"
        content: "prompts/keyword_extractor/example3_input.txt"
      - type: "image"
        content: "test_3"
      - type: "text"
        content: "prompts/keyword_extractor/example3_output.txt"

  image_descriptor:
    system_prompt: "prompts/image_descriptor/system.txt"
    task_prompt: "prompts/image_descriptor/task.txt"
    example_sequence:
      - type: "text"
        content: "prompts/image_descriptor/init_objective_define.txt"
      - type: "image"
        content: "test_1"
      - type: "text"
        content: "prompts/image_descriptor/example1_output.txt"
      # - type: "text"
      #   content: "prompts/image_descriptor/example2_input.txt"
      # - type: "image"
      #   content: "test_2"
      # - type: "text"
      #   content: "prompts/image_descriptor/example2_output.txt"
      # - type: "text"
      #   content: "prompts/image_descriptor/example3_input.txt"
      # - type: "image"
      #   content: "test_3"
      # - type: "text"
      #   content: "prompts/image_descriptor/example3_output.txt"

  toy_desc_modifier:
    system_prompt: "prompts/toy_desc_modifier/system.txt"
    task_prompt: "prompts/toy_desc_modifier/task.txt"
    example_sequence:
      - type: "text"
        content: "prompts/toy_desc_modifier/init_objective_define.txt"
      - type: "image"
        content: "test_1"
      - type: "text"
        content: "prompts/toy_desc_modifier/example1_input.txt"
      - type: "text"
        content: "prompts/toy_desc_modifier/example1_output.txt"
      - type: "image"
        content: "out_1"
      - type: "image"
        content: "out_1_v2"
      - type: "image"
        content: "test_2"
      - type: "text"
        content: "prompts/toy_desc_modifier/example2_input.txt"
      - type: "text"
        content: "prompts/toy_desc_modifier/example2_output.txt"
      - type: "image"
        content: "out_2"
      - type: "image"
        content: "out_2_v2"
      - type: "image"
        content: "test_3"
      - type: "text"
        content: "prompts/toy_desc_modifier/example3_input.txt"
      - type: "text"
        content: "prompts/toy_desc_modifier/example3_output.txt"
      - type: "image"
        content: "out_3"
      - type: image
        content: "out_3_v3"
